name: Проблема з фільтрами
description: Тут можна повідомити про сайти, для яких відсутні правила фільтрації (ви бачите рекламу, дратівливі елементи, трекери тощо), або на яких наші правила фільтрації працюють некоректно
body:
  - type: markdown
    attributes:
      value: |
        Перш, ніж створювати звіт:

        1) Переконайтеся у відсутності проблем або конфліктів з іншими розширеннями веб-браузера.
        2) Переконайтеся, що ви використовуєте лише одне розширення для блокування реклами (фільтрації контенту).
        3) Вимкніть NoScript, Ghostery, Disconnect, HTTPS Everywhere, Privacy Badger, AntiBanner, VPN розширення і повторно протестуйте (перевірте) роботу веб-сайту, з яким виникли проблеми.

  - type: textarea
    attributes:
      label: Вкажіть веб-сайт(и), з якими у вас виникли проблеми
      description: |
        Вкажіть URL-адресу веб-сайту (**ОБОВ'ЯЗКОВО**)
        Попередьте, якщо мова йде про сайт з **NSFW** контентом
      placeholder: |
        https://example.com.ua
      render: yaml
    validations:
      required: true
